lib_LIBRARIES = libzstfs.a

libzstfs_a_CPPFLAGS = -I$(top_srcdir)/include
libzstfs_a_SOURCES = \
	status.cpp \
	calendar.cpp \
	symbols.cpp \
	actions.cpp \
	store.cpp \
	history.cpp \
	market.cpp \
	markets.cpp \
	codec.cpp

nobase_include_HEADERS = \
	$(top_srcdir)/include/zstfs/status.h \
	$(top_srcdir)/include/zstfs/data.h \
	$(top_srcdir)/include/zstfs/market.h
